# Generated by Django 5.0.14 on 2026-10-08 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_team'),
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage share of the total (weights must sum to 100).', max_digits=5),
        ),
        migrations.CreateModel(
            name='JudgingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Round 1', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('cutoff_top_n', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('done', 'Done')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='competitions.competition')),
            ],
            options={
                'ordering': ['competition', 'order'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='judging_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='evaluations.judginground'),
        ),
        migrations.CreateModel(
            name='ScoreAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('old_comment', models.TextField(blank=True)),
                ('new_comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_audits', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='evaluations.score')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='judginground',
            constraint=models.UniqueConstraint(fields=('competition', 'order'), name='unique_round_order_per_competition'),
        ),
    ]
