# Generated by Django 5.0.14 on 2026-10-08 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_score_comment_alter_criterion_weight_judginground_and_more'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_assignment_per_submission_judge',
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('submission', 'judge', 'judging_round'), name='unique_assignment_per_round'),
        ),
    ]
