# Generated by Django 5.0.14 on 2026-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('competitor', 'Competitor'), ('judge', 'Judge'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
