# Generated by Django 5.0.14 on 2026-10-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.URLField(blank=True)),
                ('deployed_link', models.URLField(blank=True)),
                ('documentation', models.FileField(blank=True, upload_to='docs/')),
                ('static_file', models.FileField(blank=True, upload_to='infographics/static/')),
                ('dynamic_file', models.FileField(blank=True, upload_to='infographics/dynamic/')),
                ('dynamic_link', models.URLField(blank=True)),
                ('agree_ip', models.BooleanField(default=False)),
                ('disclose_ai', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='competitions.team')),
            ],
        ),
    ]
