# Generated by Django 5.0.14 on 2026-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('track', models.CharField(choices=[('infographics', 'Infographics'), ('hackathon', 'Hackathon'), ('high_school', 'High School')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('registration_deadline', models.DateTimeField()),
                ('submission_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('judging', 'Judging'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
